### ISSUE TITLE
README.md - Error in Prerequisites for Apt

### ISSUE THREAD

**Issue by gottsman** [vehagn/homelab#8]
A simple cut/paste of your instructions in the README prereqs point to deprecated Apt repos. Here is the relevant announcement:

https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

Here is the relevant changes that worked for me.

```
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
```

**Comment by vehagn** [comment]
Thank you for informing me.

It's fixed in the [proxmox-branch](https://github.com/vehagn/homelab/tree/proxmox) which I have to clean up a bit before merging.

If you're getting started with Kubernetes I've written an article for k3s [here](https://blog.stonegarden.dev/articles/2024/02/bootstrapping-k3s-with-cilium/) and another with Proxmox and kubeadm [here](https://blog.stonegarden.dev/articles/2024/03/proxmox-k8s-with-cilium/)
